package gui;
import controller.data_pc;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.HashMap;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
    public class datapc extends javax.swing.JFrame {
private void ViewData(){
    data_pc ck = new data_pc();
    try{
        datapcTBL.setModel(DbUtils.resultSetToTableModel(ck.Updatetbl_datapc()));
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}
    

    /**
     * Creates new form datapc
     */
    public datapc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_pcTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        merek_pcTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ramTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        penyimpananTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hargaTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        exitTB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datapcTBL = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID PC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));
        getContentPane().add(id_pcTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 230, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MEREK PC");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        merek_pcTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merek_pcTFActionPerformed(evt);
            }
        });
        getContentPane().add(merek_pcTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 230, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RAM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        ramTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramTFActionPerformed(evt);
            }
        });
        getContentPane().add(ramTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 230, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PENYIMPANAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));
        getContentPane().add(penyimpananTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 230, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HARGA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));
        getContentPane().add(hargaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 230, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 90, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 90, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 90, 30));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 90, 30));

        exitTB.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        exitTB.setText("EXIT");
        exitTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitTBActionPerformed(evt);
            }
        });
        getContentPane().add(exitTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 90, 30));

        datapcTBL.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        datapcTBL.setForeground(new java.awt.Color(51, 51, 51));
        datapcTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        datapcTBL.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datapcTBLAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                datapcTBLAncestorRemoved(evt);
            }
        });
        datapcTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datapcTBLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datapcTBL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 690, 200));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menupc.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 50, 810, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ViewData();       
    }//GEN-LAST:event_formWindowOpened

    private void exitTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitTBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitTBActionPerformed

    private void datapcTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapcTBLMouseClicked
        int row = datapcTBL.getSelectedRow();
        id_pcTF.setText(datapcTBL.getModel().getValueAt(row, 0).toString());
        merek_pcTF.setText(datapcTBL.getModel().getValueAt(row, 1).toString());
        ramTF.setText(datapcTBL.getModel().getValueAt(row, 2).toString());
        penyimpananTF.setText(datapcTBL.getModel().getValueAt(row, 3).toString());
        hargaTF.setText(datapcTBL.getModel().getValueAt(row, 4).toString());
    }//GEN-LAST:event_datapcTBLMouseClicked

    private void datapcTBLAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datapcTBLAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_datapcTBLAncestorRemoved

    private void datapcTBLAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datapcTBLAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datapcTBLAncestorAdded

    private void ramTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramTFActionPerformed

    private void merek_pcTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merek_pcTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merek_pcTFActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        id_pcTF.setText("");
        merek_pcTF.setText("");
        ramTF.setText("");
        penyimpananTF.setText("");
        hargaTF.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String ObjButtons[]={"Yes","Now"};
        int PromptResult = JOptionPane.showOptionDialog(null, "Yakin Ingin Menghapus ?", "Massage", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, ObjButtons, ObjButtons[1]);
        if(PromptResult==0){
            data_pc ck = new data_pc();
            ck.id_pc = id_pcTF.getText();
            try{
                ck.hapus();
                JOptionPane.showMessageDialog(null, "Hapus");
                ViewData();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        data_pc ck = new data_pc();
        ck.id_pc = id_pcTF.getText();
        ck.merek_pc = merek_pcTF.getText();
        ck.ram = ramTF.getText();
        ck.penyimpanan = penyimpananTF.getText();
        ck.harga = hargaTF.getText();
        try{
            ck.edit();
            JOptionPane.showMessageDialog(null, "Edit");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }ViewData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        data_pc ck = new data_pc();
        ck.id_pc = id_pcTF.getText();
        ck.merek_pc = merek_pcTF.getText();
        ck.ram = ramTF.getText();
        ck.penyimpanan = penyimpananTF.getText();
        ck.harga = hargaTF.getText();
        try{
            ck.simpan();
            JOptionPane.showMessageDialog(null, "Simpan");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }ViewData();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable datapcTBL;
    private javax.swing.JButton exitTB;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JTextField id_pcTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField merek_pcTF;
    private javax.swing.JTextField penyimpananTF;
    private javax.swing.JTextField ramTF;
    // End of variables declaration//GEN-END:variables
}
