/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import controller.data_penyewa;
import controller.data_transaksi;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.HashMap;
/**
 *
 * @author LENOVO
 */
    public class datatransaksi extends javax.swing.JFrame {
private void ViewData(){
        data_transaksi ck = new data_transaksi();
        try{
            transaksiTBL.setModel (DbUtils.resultSetToTableModel (ck.Updatetbl_transaksi()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
    }
}
        
    /**
     * Creates new form datatransaksi
     */
    public datatransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idtransaksiTF = new javax.swing.JTextField();
        idpcTF = new javax.swing.JTextField();
        idpenyewaTF = new javax.swing.JTextField();
        merekpcTF = new javax.swing.JTextField();
        hargaTF = new javax.swing.JTextField();
        sewaperjamTF = new javax.swing.JTextField();
        biayaTF = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaksiTBL = new javax.swing.JTable();
        total = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA TRANSAKSI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel1)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1000, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID TRANSAKSI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID PC");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID PENYEWA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MEREK PC");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HARGA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SEWA PER JAM");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BIAYA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));
        getContentPane().add(idtransaksiTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 330, 30));
        getContentPane().add(idpcTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 330, 30));
        getContentPane().add(idpenyewaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 330, 30));
        getContentPane().add(merekpcTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 330, 30));
        getContentPane().add(hargaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 330, 30));
        getContentPane().add(sewaperjamTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 330, 30));

        biayaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaTFActionPerformed(evt);
            }
        });
        getContentPane().add(biayaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 330, 30));

        simpan.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 110, 30));

        edit.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 150, 110, 30));

        hapus.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 110, 30));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 110, 30));

        exit.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 300, 110, 30));

        transaksiTBL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        transaksiTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        transaksiTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiTBLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transaksiTBL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 900, 250));

        total.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        total.setText("TOTAL");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 110, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaksi.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void biayaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biayaTFActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ViewData();
    }//GEN-LAST:event_formWindowOpened

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        data_transaksi ck = new data_transaksi();
        ck.id_transaksi = idtransaksiTF.getText();
        ck.id_pc = idpcTF.getText();
        ck.id_penyewa = idpenyewaTF.getText();
        ck.merek_pc = merekpcTF.getText();
        ck.harga = hargaTF.getText();
        ck.sewa_jam = sewaperjamTF.getText();
        ck.biaya = biayaTF.getText();
        try{
            ck.edit();
            JOptionPane.showMessageDialog(null, "Edit");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }ViewData();
    }//GEN-LAST:event_editActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
         data_transaksi ck = new data_transaksi();
        ck.id_transaksi = idtransaksiTF.getText();
        ck.id_pc = idpcTF.getText();
        ck.id_penyewa = idpenyewaTF.getText();
        ck.merek_pc = merekpcTF.getText();
        ck.harga = hargaTF.getText();
        ck.sewa_jam = sewaperjamTF.getText();
        ck.biaya = biayaTF.getText();
        try{
            ck.simpan();
            JOptionPane.showMessageDialog(null, "Simpan");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }ViewData();
    }//GEN-LAST:event_simpanActionPerformed

    private void transaksiTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiTBLMouseClicked
        // TODO add your handling code here:
        int row = transaksiTBL.getSelectedRow();
        idtransaksiTF.setText(transaksiTBL.getModel().getValueAt(row, 0).toString());
        idpcTF.setText(transaksiTBL.getModel().getValueAt(row, 1).toString());
        idpenyewaTF.setText(transaksiTBL.getModel().getValueAt(row, 2).toString());
        merekpcTF.setText(transaksiTBL.getModel().getValueAt(row, 3).toString());
        hargaTF.setText(transaksiTBL.getModel().getValueAt(row, 4).toString());
        sewaperjamTF.setText(transaksiTBL.getModel().getValueAt(row, 5).toString());
        biayaTF.setText(transaksiTBL.getModel().getValueAt(row, 6).toString());
    }//GEN-LAST:event_transaksiTBLMouseClicked

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        idtransaksiTF.setText("");
        idpcTF.setText("");
        idpenyewaTF.setText("");
        merekpcTF.setText("");
        hargaTF.setText("");
        sewaperjamTF.setText("");
        biayaTF.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        String ObjButtons[]={"Yes","Now"};
        int PromptResult = JOptionPane.showOptionDialog(null, "Yakin Ingin Menghapus ?", "Massage", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, ObjButtons, ObjButtons[1]);
        if(PromptResult==0){
            data_transaksi ck = new data_transaksi();
            ck.id_transaksi = idtransaksiTF.getText();
            try{
                ck.hapus();
                JOptionPane.showMessageDialog(null, "Hapus");
                ViewData();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        if(sewaperjamTF.getText().equals("") || hargaTF.getText().equals("")){
            //Input Tidak Boleh Kosong
            JOptionPane.showMessageDialog(null, "Input Tidak Boleh Kosong");
        } else {
        int sewaperjam = Integer.valueOf(sewaperjamTF.getText());
        int harga = Integer.parseInt(hargaTF.getText());
        
        int hasil = sewaperjam * harga;
     
        biayaTF.setText(Integer.toString(hasil));
        }
    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datatransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datatransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datatransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datatransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datatransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biayaTF;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JTextField idpcTF;
    private javax.swing.JTextField idpenyewaTF;
    private javax.swing.JTextField idtransaksiTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField merekpcTF;
    private javax.swing.JTextField sewaperjamTF;
    private javax.swing.JButton simpan;
    private javax.swing.JButton total;
    private javax.swing.JTable transaksiTBL;
    // End of variables declaration//GEN-END:variables
}
